apiVersion: networking.gke.io/v1alpha1
kind: FQDNNetworkPolicy
metadata:
  name: client-allow
spec:
  podSelector:
    matchLabels:
      netpol: client-allow
  egress:
  - matches:
    - name: "my-external-service.default.svc.cluster.local"
    - name: "metadata.google.internal"
    - pattern: "*.googleapis.com"
